### ISSUE TITLE
Making EvalBat round up to nearest whole number

### ISSUE THREAD

**Issue by Galikin** [adisak/EvalBat#1]
Hi Mate,

Love this little thing, I use it heaps. Running into an issue and wondering is there a way to make it round up to the nearest whole number when doing math instead of showing all the decimals? Just need that for something I'm working on. If rounding isn't possible then just leaving off any number to the right of the decimal point and only showing the whole number. Thank you!

**Comment by adisak** [comment]
If you have the most recent version, you can use the Ceil(xxx) function which is an additional math function in the script which will round a floating point expression up to the next higher Int value.  There is a similar function Floor() which rounds down (and the built in Int() conversion works to round down as well).

You can also use the VBScript function Round() to round to nearest.

**Comment by adisak** [comment]
Look at the EvalBat_vbs.vbs source code to see additional functions: comparisons, Pi(), trigonomic expressions, etc.

**Comment by Galikin** [comment]
I can't seem to get floor or ceil to work with variables trying Call EvalBat.bat Ceil (%var1%/%var2) and it just shows the answer as normal with decimals. It works when I just do something like Call EvalBat.bat Ceil (1/3).

Edit: So it seems it works if I do Call EvalBat.bat Ceil (%var1%/(any number) just doesnt seem to work for me when it's two variables, but that's ok I can work around that. :)

**Comment by adisak** [comment]
You have a typo in the example you gave: "%var2" should be "%var2%"

It is missing a % after var2

**Comment by adisak** [comment]
You have a typo in the example you gave: "%var2" should be "%var2%"

It is missing a % after var2

Try this expression:

Call EvalBat.bat Ceil ( %var1% / %var2% )

**Comment by adisak** [comment]
Tested that it works as designed even with batch variables

set aa=300
set bb=65
evalbat_echo Ceil(%aa% / %bb%)

Input: Ceil(300 / 65)
Result: 5

**Comment by adisak** [comment]
If you need to debug expressions in the future, try using EvalBat_Echo.bat instead of EvalBat.bat to see the what the input and output are being fed to EvalBat.bat by your call
