### ISSUE TITLE
Laggy when using multiple in one batch file

### ISSUE THREAD

**Issue by Galikin** [adisak/EvalBat#2]
I've noticed when using 3-4 calls to EvalBat in one section of scripting that it's a bit laggy when producing the result rather than instant. Is there anyway to remedy that?

**Comment by adisak** [comment]
Each time you run EvalBat, it runs a small vbscript program using the Windows cscript host.  There's a startup and run cost for each of those executions (disk and CPU).  The best way to speed that up is to have a SSD (solid state drive) as the main Windows drive and have the EvalBat script reside on SSD as well.  Faster access to cscript.exe and EvalBat.bat will speed up runtime using them.

**Comment by adisak** [comment]
It's primarily meant for simple computations.  If you have more complex / multiple computations that have to be done faster, you might want to consider using a custom vbscript that generates multiple results with a single invocation (using EvalBat as a template for writing your own) or writing your script in another language like python to generate multiple results.
